FROM python:3.11-alpine
WORKDIR /code

COPY ./requirements-docker.txt /code/requirements-docker.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements-docker.txt
ENV CONTAINERS_TYPE=docker

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app

ENTRYPOINT ["fastapi", "run", "app/main.py"]
CMD ["--port", "80"]
