FROM python:3.11-alpine
WORKDIR /code

COPY ./requirements-incus.txt /code/requirements-incus.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements-incus.txt
ENV CONTAINERS_TYPE=incus

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app

ENTRYPOINT ["fastapi", "run", "app/main.py"]
CMD ["--port", "80"]
